### ISSUE TITLE
JWT option in fuzzer is not shown if request doesn't contains JWT pattern

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/owasp-zap-jwt-addon#26]
**Is your feature request related to a problem? Please describe.**
JWT option in fuzzer is not shown if request doesn't contains JWT pattern. There is no indication to the user that why JWT option is unavailable. 

**Glimpse of issues**
![image](https://user-images.githubusercontent.com/13570884/134780724-857b36e1-96b0-4f03-9fbc-2b761a537e49.png)

If JWT pattern was found in the request then:
![image](https://user-images.githubusercontent.com/13570884/134780787-9ac3d880-e292-423e-920a-c0e5d982b241.png)

**To Reproduce**
Go to any request which is not having JWT pattern and then visit the fuzzer screen.

**Expected behavior**
Add the behavior details that the fuzzer will only show the JWT option if request has the valid jwt format in Readme.md and also help index (we are building this in PR: https://github.com/SasanLabs/owasp-zap-jwt-addon/issues/25)

**Comment by preetkaran20** [comment]
Hi @kingthorin @thc202,

please share your thoughts.

thanks,
Karan

**Comment by thc202** [comment]
I don't think we should show the option if it does not apply. This can be documented in the add-on, that you can only fuzz JWT tokens if there's one.

**Comment by kingthorin** [comment]
I'm okay with it only showing when applicable.

**Comment by preetkaran20** [comment]
Thanks @thc202  and @kingthorin  for your inputs. Updated the description.
