### ISSUE TITLE
Replace forked sharedutils component with use of commonlib

### ISSUE THREAD

**Issue by kingthorin** [SasanLabs/owasp-zap-jwt-addon#3]
https://github.com/SasanLabs/owasp-zap-jwt-addon/tree/master/src/main/java/org/zaproxy/zap/sharedutils -=> `    implementation("org.zaproxy.addon:commonlib:1.0.0")`

**Comment by preetkaran20** [comment]
@kingthorin  thanks a lot. will look into it. How to know what are the libraries exists in addon ? Does Fuzzer is also published under this ?

**Comment by kingthorin** [comment]
It's just a maven available replacement of sharedutils for now. We are planning to do similar for fuzz I believe. Don't have an ETA yet.
