### ISSUE TITLE
Static files leads to False positives

### ISSUE THREAD

**Issue by itsdivyanshjain** [SasanLabs/owasp-zap-jwt-addon#42]
**Describe the bug**
Currently this rule test on static files like (CSS, JS) which leads to false positive.

**Expected behavior**
Skip the test on static files

**Would you like to help fix this issue?**
Yes

**Comment by preetkaran20** [comment]
@itsdivyanshjain thanks for reporting the issue. Is it possible to add the false positive report or little bit more details so that we can understand more?

Also, please go ahead with implementation. 

thanks,
Karan
