### ISSUE TITLE
ScanRule Naming Consistency

### ISSUE THREAD

**Issue by kingthorin** [SasanLabs/owasp-zap-jwt-addon#7]
Related to: https://github.com/zaproxy/zaproxy/issues/6049

https://github.com/SasanLabs/owasp-zap-jwt-addon/blob/master/src/main/java/org/zaproxy/zap/extension/jwt/JWTActiveScanner.java should be renamed `JWTActiveScanRule` or `JwtActiveScanRule`

Of course you don't have to conform to that since this is project is 3rd party, so close/address as you see fit. But it's a pretty simple change and helps bring consistency and clarity/specificity.

**Comment by preetkaran20** [comment]
@kingthorin Sure will take care of this.

**Comment by Keenal** [comment]
I will like to work on this, please let me know if I can!

**Comment by preetkaran20** [comment]
Hi @Keenal , 

Assigned it to you. 
Thanks, 
Karan

**Comment by Keenal** [comment]
Done! #13
